Repository kabirbaidhya/keycode-js, pull requests merged in 2019-07, with the labels that each got.

#18 Remove npm-run-all and other unused dependencies
  package.json
  yarn.lock
Labels: dependencies

#19 Use eslint-config-leapfrog for eslint configuration
  .eslintrc
  .travis.yml
  dist/keycode.min.js
  dist/keycode.min.js.map
  package.json
  yarn.lock
Labels: dependencies

#20 Run tests for both original library and the generated build
  .editorconfig
  .eslintrc
  package.json
  rollup.config.js
  test/KeyCode.spec.js
Labels: test

#22 Remove deprecated options from rollup config
  rollup.config.js
Labels: enhancement

#23 Change unpkg URL to next version when creating changelog
  t
Labels: enhancement
