Repository kabirbaidhya/keycode-js, pull requests merged in 2019-08, with the labels that each got.

#24 Make keycode-js compatible with deno
  .editorconfig
  .eslintrc
  .gitignore
  .npmignore
  .travis.yml
  dist/keycode.cjs.js
  dist/keycode.es6.js
  dist/keycode.min.js
  dist/keycode.min.js.map
  index.js
  lib/KeyCode.js
  mod.d.ts
  mod.spec.js
  mod.ts
  package.json
  rollup.config.js
  test.ts
  tsconfig.json
  yarn.lock
Labels: feature, refactor

#27 Include docs for usage with deno
  README.md
Labels: documentation

#28 Test and build enhancements for node, deno and browser builds
  .gitignore
  README.md
  mod.d.ts
  mod.spec.js
  package.json
  rollup.config.js
  t
  test.ts
  test/browser.test.html
  test/browser.test.js
  test/deno.test.ts
  test/node.test.js
  test/tests.ts
  tsconfig.json
  yarn.lock
Labels: test

#29 Use named export for ES2015
  README.md
  package.json
Labels: documentation

#31 Make the main build (common js) fully-compatible with ES5
  dist/keycode.cjs.js
  rollup.config.js
  tsconfig.json
Labels: bugfix
